services:
  php-apache:
    build:
      context: ./docker/php-apache        
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ./:/var/www
    depends_on:
      - db   
    networks:
        - rede

  php-dev:
    build:
      context: ./docker/php-dev
    ports:
       - "${PHP_DEV_PORT}:8000"
       - "5173:5173"
    volumes:
      - ./:/home/dev
    env_file:
      - .env    
    depends_on:
       - db
    networks:
        - rede


  db:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
       - "3306:3306"      
    volumes:
      - mysql_data:/var/lib/mysql  # Volume nomeado do Docker

    networks:
        - rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
        - rede

networks:
    rede:
        driver: bridge

volumes:
  mysql_data:  # Declarando o volume
    name: mysql_data
    external: true