services:
  php-apache:
    build:
      context: ./docker/php-apache        
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ./:/var/www
    depends_on:
      - db   
    networks:
        - rede
        # - rede_windows
        #     ipv4_address: 192.168.15.10

  php-dev:
    build:
      context: ./docker/php-dev
    ports:
       - "5173:5173"      
       - "8000:8000"
    volumes:
      - ./:/home/dev
    env_file:
      - .env    
    depends_on:
       - db
    networks:
        - rede


  db:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
       - "3306:3306"      
    volumes:
      - mysql_data:/var/lib/mysql  # Volume nomeado do Docker
      #- ~/docker/volumes/mysql:/var/lib/mysql # Bind mount no diretório local
    networks:
        - rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
    - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
        - rede
  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "${NGINX_PORT}:80"
  #   volumes:
  #     - ../src:/var/www/html
  #   depends_on:
  #    - php
  # php:
  #  build:
  #    context: ./docker/php-fpm
  #  ports:
  #    - "9000:9000"
  #  expose:
  #   - 9000  # Porta do php-fpm      
  #  volumes:
  #    - ./src:/var/www/html
  #  depends_on:
  #    - db
  # redis:
  #     image: redis:latest
  #     networks:
  #         - rede

networks:
    rede:
        driver: bridge
    # rede_windows:
    #   driver: macvlan
    #   driver_opts:
    #     parent: eth0 # Substitua por sua interface de rede
    #   ipam:
    #     config:
    #       - subnet: 192.168.1.0/24  # Sub-rede que desejamos usar
    #         gateway: 192.168.1.1      # Gateway para a rede


volumes:
  mysql_data:  # Declarando o volume
    name: mysql_data
    external: true